### ISSUE TITLE
管理OpenID绑定

### ISSUE THREAD

**Issue by greatghoul** [ScriptFan/ScriptFan.com#10]
开发OpenID绑定管理的页面，在资料修改页面的侧边样中已经预留的链接
1. 添加绑定Google OpenID
2. 解除绑定Google OpenID
3. 如果是OpenID自动创建的用户，在设置密码之前，不允许解除绑定，否则会导致用户成为被遗忘都，无法登陆。

**Comment by dynamojinz** [comment]
这个我现在正在弄，刚做完解除绑定的，添加绑定的功能完成后再提交上来

**Comment by darth30joker** [comment]
@greatghoul 看看提交, 是否是咱们需要的.
如果有问题, 就在这里提出来, 让 @dynamojinz 继续完成
如果没有问题, 那么close掉这个issue
