### ISSUE TITLE
开发新闻功能

### ISSUE THREAD

**Issue by greatghoul** [ScriptFan/ScriptFan.com#12]
因为一些原因，我们的项目进度有些缓慢，scriptfan.com 域名长期闲置也不是件好事，所以和 @kingheaven 商量是否要先开发出发表日志的功能。

讨论下日志的具体用处：
1. 发表一些新闻，公告
2. 在活动栏目上线前，充当活动发布的功能
3. 转载一些成员的日志（是否必要）
### 开发进度
- [x] 发布/编辑文章
- [x] 文章列表
- [x] 按分类过滤的文章列表
- [x] 文章列表分页
- [x] 文章内容这样大段的 Markdown，更新时转为 html，存在 content_html 中，避免每次转换。
- [x] 移除文章分类表，添加文章标签相关表
- [x] 添加标签相关的 Model 及
- [x] 文章发布时可以添加标签
- [x] 文章编辑时可以维护标签
- [ ] 发送/编辑文章的权限控制

**Comment by darth30joker** [comment]
目前还差多少, 请更新一下进度.

**Comment by greatghoul** [comment]
关于 **发送/编辑文章的权限控制** 这个统一在后面加。
