### ISSUE TITLE
讨论权限模型

### ISSUE THREAD

**Issue by greatghoul** [ScriptFan/ScriptFan.com#14]
以前和 @kingheaven  讨论的权限设计，只有两个角色类型
- 3 - 普通用户（目前只能浏览）
- 4 - 管理员（发布新闻，活动什么的）

其它的枚举值留给别的角色，这样的设计非常简单，但目前来说，能够满足基本需要。

``` python
class User(db.Model):
    # ...
    #: 简单的权限控制，控制级别：3-普通用户 4-管理员 (目前就这么简单，后面再讨论）
    privilege = db.Column(db.Integer, default=3)
```

大家可以讨论一下，怎么实现比较好。

**Comment by darth30joker** [comment]
5 - 超级管理员
1 - 被封的用户 (不要删除, 留着这些用户, 防止他们登陆)

**Comment by darth30joker** [comment]
暂时就这么定了:
1. 被封用户, 永远不能登陆
2. 保留
3. 普通用户
4. 普通管理员
5. 超级管理员
