### ISSUE TITLE
讨论：文章使用标签还是分类

### ISSUE THREAD

**Issue by greatghoul** [ScriptFan/ScriptFan.com#16]
在 Commit: ed7c5cc930334dd826105995546f9d96322b35a2 中，我去除了文章类型，仅使用了分类来管理文章，尽量使文章发布变得简单。

@kingheaven 提出使用分类管理文章是否有意义。

我想我们可以来讨论一下。

现在很多博客系统都已经弱化了分类 ，包括我的 [博客](http://www.g2w.me) 也是如此，很多时候，分类不足以描述一篇文章的归属。

于是一些文章系统仅保留标签来管理文章，对于文章归属的定义，灵活许多。

就咱们 GDG 的真实需求来说，发表文章大概也只有新闻和通告两种，至于博客，大部分人会选择在自己的博客中发表， scriptfan 来全文转载吧，也没有什么意义。

所以对文章类型的管理，需求并不怎么大，所以只保留分类或者只采用标签就足够了。

至于具体是使用分类还是使用标签，大家发表下看法吧。

**Comment by darth30joker** [comment]
才发现这个issue还没有人讨论呢啊

我提一个建议, 就是我们可以设置一些常用的tag, 发文章的时候, 可以把它们放上去, 只要一点, 就会出现在tag框里(目前还没有tag框哦). 这样的好处是: 将这些常用tag当做category来用; 省去了每次打tag的麻烦; 设计上统一, 只有tag.

**Comment by greatghoul** [comment]
使用 Tag 也好，一般来说，做 Tag，对于传统数据库模型，表设计成什么样比较好一些？

**Comment by darth30joker** [comment]
一般来说, 都是多对多的设计

**Comment by greatghoul** [comment]
已经实现了文章标签的功能。
