### ISSUE TITLE
本地跑应用，内在占用居高不下

### ISSUE THREAD

**Issue by greatghoul** [ScriptFan/ScriptFan.com#26]
不知道什么原因，这几天跑应用的时候，ScriptFan 页面的内存占用很高。

如下图，竟然占用到了 `708,000K` ，对于一个连 js 都没有的页面，这个内存占用有些夸张。

![20130329225038](https://f.cloud.github.com/assets/208966/317776/a6f7c5e4-9880-11e2-8847-1612884aef39.png)

大家在开发时有没有遇到过这样的情况。

**Comment by darth30joker** [comment]
是有些夸张, 你文章数应该也不多吧

**Comment by greatghoul** [comment]
我在想，难道是我开了 flask 多线程的原因？不过要内存消夏大也应该是 python 进程呀，怎么也轮不到 Chrome 呀。

**Comment by darth30joker** [comment]
是的

所以有些奇怪, 看看js, 是不是js的问题呢
