### ISSUE TITLE
根据greatghoul的新user表，修改了相应的资料修改页面

### ISSUE THREAD

**Issue by dynamojinz** [ScriptFan/ScriptFan.com#6]
也不知道跟你的思路是否一致，先改一点吧。以前都是一个人写代码，第一次合作写，多多指教哈

**Comment by greatghoul** [comment]
改的不错，我还在你的基础上进一步修改了，修正了一些字段命名。将 ajax 提交改为普通方式提交，并使用规范的 form <==> model 传值方式。  2373ea6d4d905fcc3f77265a8bb6b3328092ac70
