### ISSUE TITLE
OpenID的处理方式改动

### ISSUE THREAD

**Issue by greatghoul** [ScriptFan/ScriptFan.com#7]
对于使用Google OpenID登陆，我之前是这样处理的。

```
    (开始)  
      |  
点击使用Google登陆   
      |
 返回用户信息  
      |                   (否)  
查找此OpenID是否绑定用户  ---->  跳转注册页面并填入返回的相关信息 ----> 用户注册  
      |（是）                                                          |  
      +------------------------> 登陆该用户 <--------------------------+  
                                     |  
                                  (结束)  
```

即便使用了OpenID，也跳不过注册这一步，所以我现在想，是不是在用户点击使用OpenID登陆时。
先是查数据库，是否绑定过，如果绑定过直接登陆。如果没有，直接为该OpenID新建一个空用户（只有ID）等一些必要信息，然后绑定该OpenID，并自动以该用户登陆。

这样看似后台做了那么多，对用户来说，只是一次点击的时间而已。
如果用户希望设置密码，可以在密码修改页面去设置。

大家谈谈想法吧。

**Comment by dynamojinz** [comment]
你这个方案中，我觉得在openid用户第一次登录后，跳到用户资料页面完善一下资料更好

**Comment by darth30joker** [comment]
目前代码段的处理方式是：
1. 让用户用OpenID登陆（不管是新注册还是登陆，都跟网站没关系，都是OpenID网站来处理）
2. 登陆成功后，得到用户的OpenID（是一个字符串），然后去数据库查找有没有用户的OpenID和这个相同
3. 有，则把该用户的信息读出来，让用户在网站登陆成功
4. 没有，则为该用户在网站注册一个账号（系统自动完成，不需要用户参与，昵称等信息，可以从OpenID返回的信息读出来）

**Comment by greatghoul** [comment]
那么我就依照代码段的方式来处理吧。

2012/12/1 David Xie notifications@github.com

> 目前代码段的处理方式是：
> 1. 让用户用OpenID登陆（不管是新注册还是登陆，都跟网站没关系，都是OpenID网站来处理）
> 2. 登陆成功后，得到用户的OpenID（是一个字符串），然后去数据库查找有没有用户的OpenID和这个相同
> 3. 有，则把该用户的信息读出来，让用户在网站登陆成功
> 4. 没有，则为该用户在网站注册一个账号（系统自动完成，不需要用户参与，昵称等信息，可以从OpenID返回的信息读出来）
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/kingheaven/ScriptFan.com/issues/7#issuecomment-10917663.

## 

greatghoul http://www.g2w.me - Ask and Learn

**Comment by greatghoul** [comment]
你把其他人也邀请进 Tower.im 吧，方便协调工作。

2012/12/1 greatghoul greatghoul@gmail.com

> 那么我就依照代码段的方式来处理吧。

## 

greatghoul http://www.g2w.me - Ask and Learn
