### ISSUE TITLE
使用i18n做message的处理

### ISSUE THREAD

**Issue by darth30joker** [ScriptFan/ScriptFan.com#8]
除了可以应付多语言，更多的是让页面中不再出现硬编码的message
先assign给我自己了，明天来加，然后告诉大家怎么用，大家以后就follow这个了

**Comment by greatghoul** [comment]
使用的是这个吗？
https://github.com/mitsuhiko/flask-babel/

**Comment by darth30joker** [comment]
是的~

**Comment by greatghoul** [comment]
好的，我这会儿还在做一些修改，一会儿就必完了，然后你明天 pull 下来加 i18n
最近再在 wiki 中写一个国际化的命名约定，大家 follow 你的那个约定来走，不至因为彼此习惯不同，导致混乱。

On Sat, Dec 1, 2012 at 10:48 PM, David Xie notifications@github.com wrote:

> 是的~
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/kingheaven/ScriptFan.com/issues/8#issuecomment-10917909.

## 

greatghoul http://www.g2w.me - Ask and Learn

**Comment by darth30joker** [comment]
已经添加成功，提交在：https://github.com/kingheaven/ScriptFan.com/commit/7e731151d25d94dd70cc05b4e9164a4b7d85e50f
各位在dev分支下更新即可得到

命名没有特别的规范，只是注意把英文写对即可，我们这里用的不是简单的key=>value的翻译，而是纯英文的翻译，即任何待翻译的英文，都必须是正规的，可读的英文，这样，即使语言文件里没有这个翻译，也会显示可读的英文

**Comment by darth30joker** [comment]
@greatghoul 来看一下，如果我提交的方法正确，那么这个issue就可以close了

**Comment by darth30joker** [comment]
长时间没有反馈, 关闭该issue
大家开发的时候, 页面中所有的东西, 注意使用多语言

**Comment by darth30joker** [comment]
与 @greatghoul 交流后, 发现现在有2种对待翻译的方式:
1. Key为关键字的方式, 需要对每一个key进行翻译.
   坏处: 当翻译不存在时, key会直接显示出来. 
   好处: 当翻译需要改变时, 不用改key的名字.
2. Key为直接可读的英文的方式, 不需要英语的翻译.
   好处: 需要多语言的地方, 直接写的是英语, 所以, 不需要英语的语言文件也可以. 同时, 翻译不存在的时候, 不会显示key名, 显示的直接是可读的英文.
   坏处: 当翻译需要改变的时候, 需要改key的名字

大家来投票吧, 看哪种更合适一些. 邱健童鞋推荐第一种, 我个人觉得各有优缺点, 如果考虑以后修改的可能性的话, 貌似第一种更好. 大家的意见呢?

**Comment by greatghoul** [comment]
其实在很多时候，提示信息是动态的，比如 "XX创建成功" 这是一个整体，当然，可能 Message 中可能不止一个变量 。有时候语句还需要调整，这种方式，用 key 比较好一些，还有存在加粗，链接等一此格式下，key 也相对好一此。

**Comment by dynamojinz** [comment]
这么说来第一种好点，我原来用第二种都是用来生成gui菜单按钮什么的，没有考虑这些复杂的情况
在 2013-2-26 下午10:51，"greatghoul" notifications@github.com写道：

**Comment by greatghoul** [comment]
如果是用 Key 的形式，可以在里面加一些比如 %s, %(event_name)s 之类的变量了。命名空间也比较好规划，也比较好找一些。

**Comment by dynamojinz** [comment]
有道理，那我也投1吧
在 2013-2-26 下午11:19，"greatghoul" notifications@github.com写道：

**Comment by darth30joker** [comment]
已经两个人投1了, 那么我也赞成1了, 毕竟也是有好处的

我这就去改所有的i18n

On Tue, Feb 26, 2013 at 11:25 PM, dynamojinz notifications@github.comwrote:

> 有道理，那我也投1吧
> 在 2013-2-26 下午11:19，"greatghoul" notifications@github.com写道：
> 
> > 如果是用 Key 的形式，可以在里面加一些比如 %s, %(event_name)s 之类的变量了。
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ScriptFan/ScriptFan.com/issues/8#issuecomment-14119730>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ScriptFan/ScriptFan.com/issues/8#issuecomment-14120132
> .

## 

---

Best Regards,
David Xie
Founder of ScriptFan technology community - http://scriptfan.com
Manager of Xi'an GDG (Google Developer Group)
http://about.me/davidx

---

Everything happens for a reason. Attitude determines everything!

**Comment by darth30joker** [comment]
新增加了一个shell脚本去更新翻译, 提交在 https://github.com/ScriptFan/ScriptFan.com/commit/be83c2d06c88c1d95567937b57ed8e4ba1fbcd2d
